/** Nimbus OAuth2/OIDC and its non-modular runtime dependencies. */
module oauth2.oidc.sdk {
    requires transitive com.nimbusds.jose.jwt;
    requires transitive org.objectweb.asm;
    requires transitive java.xml;

    exports com.nimbusds.common.contenttype;
    exports com.nimbusds.langtag;
    exports com.nimbusds.oauth2.sdk;
    exports com.nimbusds.oauth2.sdk.as;
    exports com.nimbusds.oauth2.sdk.assertions;
    exports com.nimbusds.oauth2.sdk.assertions.jwt;
    exports com.nimbusds.oauth2.sdk.assertions.saml2;
    exports com.nimbusds.oauth2.sdk.auth;
    exports com.nimbusds.oauth2.sdk.auth.verifier;
    exports com.nimbusds.oauth2.sdk.ciba;
    exports com.nimbusds.oauth2.sdk.client;
    exports com.nimbusds.oauth2.sdk.cnf;
    exports com.nimbusds.oauth2.sdk.device;
    exports com.nimbusds.oauth2.sdk.dpop;
    exports com.nimbusds.oauth2.sdk.dpop.verifiers;
    exports com.nimbusds.oauth2.sdk.http;
    exports com.nimbusds.oauth2.sdk.id;
    exports com.nimbusds.oauth2.sdk.jarm;
    exports com.nimbusds.oauth2.sdk.jose;
    exports com.nimbusds.oauth2.sdk.pkce;
    exports com.nimbusds.oauth2.sdk.rar;
    exports com.nimbusds.oauth2.sdk.token;
    exports com.nimbusds.oauth2.sdk.tokenexchange;
    exports com.nimbusds.oauth2.sdk.util;
    exports com.nimbusds.oauth2.sdk.util.date;
    exports com.nimbusds.oauth2.sdk.util.singleuse;
    exports com.nimbusds.oauth2.sdk.util.tls;
    exports com.nimbusds.openid.connect.sdk;
    exports com.nimbusds.openid.connect.sdk.assurance;
    exports com.nimbusds.openid.connect.sdk.assurance.claims;
    exports com.nimbusds.openid.connect.sdk.assurance.evidences;
    exports com.nimbusds.openid.connect.sdk.assurance.evidences.attachment;
    exports com.nimbusds.openid.connect.sdk.assurance.request;
    exports com.nimbusds.openid.connect.sdk.claims;
    exports com.nimbusds.openid.connect.sdk.federation;
    exports com.nimbusds.openid.connect.sdk.federation.api;
    exports com.nimbusds.openid.connect.sdk.federation.config;
    exports com.nimbusds.openid.connect.sdk.federation.entities;
    exports com.nimbusds.openid.connect.sdk.federation.policy;
    exports com.nimbusds.openid.connect.sdk.federation.policy.language;
    exports com.nimbusds.openid.connect.sdk.federation.policy.operations;
    exports com.nimbusds.openid.connect.sdk.federation.registration;
    exports com.nimbusds.openid.connect.sdk.federation.trust;
    exports com.nimbusds.openid.connect.sdk.federation.trust.constraints;
    exports com.nimbusds.openid.connect.sdk.federation.trust.marks;
    exports com.nimbusds.openid.connect.sdk.federation.utils;
    exports com.nimbusds.openid.connect.sdk.id;
    exports com.nimbusds.openid.connect.sdk.nativesso;
    exports com.nimbusds.openid.connect.sdk.op;
    exports com.nimbusds.openid.connect.sdk.rp;
    exports com.nimbusds.openid.connect.sdk.rp.statement;
    exports com.nimbusds.openid.connect.sdk.token;
    exports com.nimbusds.openid.connect.sdk.validators;
    exports com.nimbusds.secevent.sdk.claims;
    exports net.minidev.asm;
    exports net.minidev.asm.ex;
    exports net.minidev.json;
    exports net.minidev.json.annotate;
    exports net.minidev.json.parser;
    exports net.minidev.json.reader;
    exports net.minidev.json.writer;
}
