module org.bouncycastle.pkix {
    requires java.logging;
    requires java.naming;
    
    requires static java.sql;

    exports org.bouncycastle.cert;
    exports org.bouncycastle.cmc;
    exports org.bouncycastle.cms;
    exports org.bouncycastle.dvcs;
    exports org.bouncycastle.eac;
    exports org.bouncycastle.est;
    exports org.bouncycastle.mime;
    exports org.bouncycastle.mozilla;
    exports org.bouncycastle.openssl;
    exports org.bouncycastle.operator;
    exports org.bouncycastle.pkcs;
    exports org.bouncycastle.pkix;
    exports org.bouncycastle.tsp;
    exports org.bouncycastle.voms;
    exports org.bouncycastle.cert.bc;
    exports org.bouncycastle.cert.cmp;
    exports org.bouncycastle.cert.crmf;
    exports org.bouncycastle.cert.crmf.bc;
    exports org.bouncycastle.cert.crmf.jcajce;
    exports org.bouncycastle.cert.dane;
    exports org.bouncycastle.cert.dane.fetcher;
    exports org.bouncycastle.cert.jcajce;
    exports org.bouncycastle.cert.ocsp;
    exports org.bouncycastle.cert.ocsp.jcajce;
    exports org.bouncycastle.cert.path;
    exports org.bouncycastle.cert.path.validations;
    
    exports org.bouncycastle.cert.selector;
    exports org.bouncycastle.cert.selector.jcajce;
    
    exports org.bouncycastle.jcajce;
    exports org.bouncycastle.jcajce.interfaces;
    exports org.bouncycastle.jcajce.io;
    exports org.bouncycastle.jcajce.provider.asymmetric;
    exports org.bouncycastle.jcajce.provider.asymmetric.dh;
    exports org.bouncycastle.jcajce.provider.asymmetric.dsa;
    exports org.bouncycastle.jcajce.provider.asymmetric.dstu;
    exports org.bouncycastle.jcajce.provider.asymmetric.ec;
    exports org.bouncycastle.jcajce.provider.asymmetric.ecghost;
    exports org.bouncycastle.jcajce.provider.asymmetric.ecghost12;
    exports org.bouncycastle.jcajce.provider.asymmetric.edec;
    exports org.bouncycastle.jcajce.provider.asymmetric.elgamal;
    exports org.bouncycastle.jcajce.provider.asymmetric.gost;
    exports org.bouncycastle.jcajce.provider.asymmetric.ies;
    exports org.bouncycastle.jcajce.provider.asymmetric.rsa;
    exports org.bouncycastle.jcajce.provider.asymmetric.util;
    exports org.bouncycastle.jcajce.provider.asymmetric.x509;
    exports org.bouncycastle.jcajce.provider.config;
    exports org.bouncycastle.jcajce.provider.digest;
    exports org.bouncycastle.jcajce.provider.drbg;
    exports org.bouncycastle.jcajce.provider.keystore;
    exports org.bouncycastle.jcajce.provider.keystore.bc;
    exports org.bouncycastle.jcajce.provider.keystore.bcfks;
    exports org.bouncycastle.jcajce.provider.keystore.pkcs12;
    exports org.bouncycastle.jcajce.provider.symmetric;
    exports org.bouncycastle.jcajce.provider.symmetric.util;
    exports org.bouncycastle.jcajce.provider.util;
    exports org.bouncycastle.jcajce.spec;
    exports org.bouncycastle.jcajce.util;
    
    
    exports org.bouncycastle.crypto.agreement;
    exports org.bouncycastle.crypto.agreement.jpake;
    exports org.bouncycastle.crypto.agreement.kdf;
    exports org.bouncycastle.crypto.agreement.srp;
    exports org.bouncycastle.crypto.commitments;
    exports org.bouncycastle.crypto.digests;
    exports org.bouncycastle.crypto.ec;
    exports org.bouncycastle.crypto.engines;
    exports org.bouncycastle.crypto.encodings;
    exports org.bouncycastle.crypto.generators;
    exports org.bouncycastle.crypto.io;
    exports org.bouncycastle.crypto.kems;
    exports org.bouncycastle.crypto.macs;
    exports org.bouncycastle.crypto.modes;
    exports org.bouncycastle.crypto.modes.gcm;
    exports org.bouncycastle.crypto.modes.kgcm;
    exports org.bouncycastle.crypto.paddings;
    exports org.bouncycastle.crypto.params;
    exports org.bouncycastle.crypto.parsers;
    exports org.bouncycastle.crypto.prng;
    exports org.bouncycastle.crypto.prng.drbg;
    exports org.bouncycastle.crypto.signers;
    exports org.bouncycastle.crypto.util;
    
    
    exports org.bouncycastle.cms.bc;
    exports org.bouncycastle.cms.jcajce;
    exports org.bouncycastle.eac.jcajce;
    exports org.bouncycastle.eac.operator;
    exports org.bouncycastle.eac.operator.jcajce;
    exports org.bouncycastle.est.jcajce;
    exports org.bouncycastle.mime.encoding;
    exports org.bouncycastle.mime.smime;
    exports org.bouncycastle.mozilla.jcajce;
    exports org.bouncycastle.openssl.bc;
    exports org.bouncycastle.openssl.jcajce;
    exports org.bouncycastle.operator.bc;
    exports org.bouncycastle.operator.jcajce;
    exports org.bouncycastle.pkcs.bc;
    exports org.bouncycastle.pkcs.jcajce;
    exports org.bouncycastle.pkix.jcajce;
    exports org.bouncycastle.tsp.cms;
}
