name: Build GuicedEE Modular Services
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
jobs:
  AOP:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Google/aop/'
      name: 'AOP Alliance'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  BCrypt:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/bcrypt/'
      name: 'BCrypt'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Guice:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - AOP
    with:
      baseDir: 'Google/guice-core/'
      name: 'Guice'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Guice-AssistedInject:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-assistedinject/'
      name: 'Guice Assisted Inject'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Guice-Grapher:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-grapher/'
      name: 'Guice Grapher'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Guice-JMX:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-jmx/'
      name: 'Guice JMX'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Guice-JNDI:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-jndi/'
      name: 'Guice JNDI'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Commons-Collections:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Apache/Commons/commons-collections/'
      name: 'Commons Collections'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Commons-BeanUtils:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs: Commons-Collections
    with:
      baseDir: 'Apache/Commons/commons-beanutils/'
      name: 'Commons Bean Utilities'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Commons-CSV:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Apache/Commons/commons-csv/'
      name: 'Commons CSV'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Commons-FileUpload:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Apache/Commons/commons-fileupload/'
      name: 'Commons File Upload'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Commons-Math:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Apache/Commons/commons-math/'
      name: 'Commons Math'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Apache-POI:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Apache/POI/apache-poi/'
      name: 'Apache POI'
      publishToCentral: ${{inputs.centralRelease}}
    needs:
      - Commons-Math
      - Commons-Collections
    secrets: inherit
  Apache-POI-OOXML:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Apache/POI/apache-poi-ooxml/'
      name: 'Apache POI OOXML'
      publishToCentral: ${{inputs.centralRelease}}
    needs:
      - Apache-POI
    secrets: inherit
  Jandex:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/jandex/'
      name: 'Jandex'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JavAssist:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/javassist/'
      name: 'JavAssist'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JSON:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/json/'
      name: 'json'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Mapstruct:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/mapstruct/'
      name: 'mapstruct'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JACC:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Jakarta/jakarta-security-jacc/'
      name: 'JACC'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  UA-Detector:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/uadetector-core/'
      name: 'UA Detector Core'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  UA-Detector-Resources:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - UA-Detector
    with:
      baseDir: 'Libraries/uadetector-resources/'
      name: 'UA Detector Resources'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JNA-Platform:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'JNI/jna-platform/'
      name: 'JNA Platform'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Azure-Identity:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Database/msal4j/'
      name: 'Microsoft Azure Identity'
      publishToCentral: ${{inputs.centralRelease}}
    needs: JNA-Platform
    secrets: inherit
  MSSQL-JDBC:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Azure-Identity
    with:
      baseDir: 'Database/mssql-jdbc/'
      name: 'SQL Server JDBC'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Postgres-SQL:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Database/postgresql/'
      name: 'Postgres SQL'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JavaNRSerialPort:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs: JNA-Platform
    with:
      baseDir: 'JNI/nrjavaserial/'
      name: 'Java NR Serial Port'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JCache:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'JCache/cache-api/'
      name: 'JCache JSR-107'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JCache-Annotations-Common:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs: JCache
    with:
      baseDir: 'JCache/cache-annotations-ri-common/'
      name: 'JCache Common Annotations'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  JCache-Annotations-Guice:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - JCache-Annotations-Common
    with:
      baseDir: 'JCache/cache-annotations-ri-guice/'
      name: 'JCache Guice'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  OpenPDF:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/openpdf/'
      name: 'Open PDF'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Metrics:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'MicroProfile/metrics-core/'
      name: 'MicroProfile Metrics'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  OpenAPI:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/swagger/'
      name: 'Open API'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  CXF-Security:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - CXF-Core
    with:
      baseDir: 'Apache/CXF/apache-cxf-rt-security/'
      name: 'CXF Security'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  CXF-Http-Transport:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - CXF-Core
      - CXF-Security
    with:
      baseDir: 'Apache/CXF/apache-cxf-rt-transports-http/'
      name: 'CXF Http Transport'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  CXF-Core:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Apache/CXF/apache-cxf/'
      name: 'CXF'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  CXF-Rest:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - CXF-Http-Transport
    with:
      baseDir: 'Apache/CXF/apache-cxf-rest/'
      name: 'CXF Rest'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  CXF-Rest-OpenAPI:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - CXF-Rest
      - OpenAPI
    with:
      baseDir: 'Apache/CXF/apache-cxf-rest-openapi/'
      name: 'CXF OpenAPI'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  RabbitMQ:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/rabbitmq-client/'
      name: 'RabbitMQ AMQP Client'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Hibernate-Core:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Jandex
    with:
      baseDir: 'Hibernate/hibernate-core/'
      name: 'Hibernate Core'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Hibernate-Validator:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Hibernate/hibernate-validator/'
      name: 'Hibernate Validator'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Hibernate-Reactive:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Hibernate-Core
    with:
      baseDir: 'Hibernate/hibernate-reactive/'
      name: 'Hibernate Reactive'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Hibernate-JCache:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - JCache-Annotations-Guice
      - Hibernate-Core
    with:
      baseDir: 'Hibernate/hibernate-jcache/'
      name: 'Hibernate JCache'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Hibernate-C3PO:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Hibernate-Core
    with:
      baseDir: 'Hibernate/hibernate-c3p0/'
      name: 'Hibernate C3P0'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Kafka-Client:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/kafka-client/'
      name: 'Kafka Client'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  TestContainers:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/testcontainers/'
      name: 'Test Containers'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Scram:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/scram/'
      name: 'Scram'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Hazelcast:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - JCache
      - Hibernate-Core
    with:
      baseDir: 'JCache/hazelcast/'
      name: 'Hazelcast'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  Hazelcast-Hibernate:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Hazelcast
      - Hibernate-JCache
    with:
      baseDir: 'JCache/hazelcast-hibernate/'
      name: 'Hazelcast Hibernate'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
#  Json-Representation:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - Guiced-Inject-Client
#    with:
#      baseDir: 'Representations/JsonRepresentation/'
#      name: 'JSON Representation'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  XML-Representation:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - Json-Representation
#    with:
#      baseDir: 'Representations/XmlRepresentation/'
#      name: 'XML Representation'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  Excel-Representation:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - Json-Representation
#    with:
#      baseDir: 'Representations/ExcelRepresentation/'
#      name: 'Excel Representation'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  MicroProfileConfig:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'MicroProfile/config-core/'
      name: 'MicroProfile Config'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  VertxMutiny:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Vert.x/vertx-mutiny/'
      name: 'Vert.x Mutiny'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  VertxRabbit:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Vert.x/vertx-rabbitmq/'
      name: 'Vert.x RabbitMQ'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  EhCache:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - JCache
    with:
      baseDir: 'JCache/ehcache/'
      name: 'EhCache'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  CloudEvents:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/cloudevents/'
      name: 'CloudEvents'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  IBM-MQ:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Libraries/ibm-mq/'
      name: 'IBM MQ Jakarta Client'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  MicroProfileHealth:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'MicroProfile/health-core/'
      name: 'MicroProfile Health'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
  MicroProfileTelemetry:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'MicroProfile/telemetry-core/'
      name: 'MicroProfile Telemetry'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit



