name: Maven Package (BOM)
on:
  workflow_dispatch:
jobs:
  AOP:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Google/aop/'
      name: 'AOP Alliance'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guava:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Google/guava/'
      name: 'Guava'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guice:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Guava
      - AOP
    with:
      baseDir: 'Google/guice-core/'
      name: 'Guice'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guice-Persist:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-persist/'
      name: 'Guice Persist'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guice-Servlet:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-servlet/'
      name: 'Guice Servlet'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guice-AssistedInject:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-assistedinject/'
      name: 'Guice Assisted Inject'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guice-Grapher:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-grapher/'
      name: 'Guice Grapher'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guice-JMX:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-jmx/'
      name: 'Guice JMX'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Guice-JNDI:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Guice
    with:
      baseDir: 'Google/guice-jndi/'
      name: 'Guice JNDI'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Commons-Collections:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Apache/Commons/commons-collections/'
      name: 'Commons Collections'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Commons-BeanUtils:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs: Commons-Collections
    with:
      baseDir: 'Apache/Commons/commons-beanutils/'
      name: 'Commons Bean Utilities'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Commons-Codec:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Apache/Commons/commons-codec/'
      name: 'Commons Codec'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Commons-CSV:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Apache/Commons/commons-csv/'
      name: 'Commons CSV'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Commons-FileUpload:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Apache/Commons/commons-fileupload/'
      name: 'Commons File Upload'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Commons-Math:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Apache/Commons/commons-math/'
      name: 'Commons Math'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Apache-POI:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Apache/POI/apache-poi/'
      name: 'Apache POI'
    needs:
      - Commons-Math
      - Commons-Codec
      - Commons-Collections
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Apache-POI-OOXML:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Apache/POI/apache-poi-ooxml/'
      name: 'Apache POI OOXML'
    needs:
      - Apache-POI
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Jandex:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Libraries/jandex/'
      name: 'Jandex'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  JavAssist:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Libraries/javassist/'
      name: 'JavAssist'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  JSON:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Libraries/json/'
      name: 'json'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  Mapstruct:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Libraries/mapstruct/'
      name: 'mapstruct'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  JACC:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Jakarta/jakarta-security-jacc/'
      name: 'JACC'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  UA-Detector:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Libraries/uadetector-core/'
      name: 'UA Detector Core'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  UA-Detector-Resources:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - UA-Detector
    with:
      baseDir: 'Libraries/uadetector-resources/'
      name: 'UA Detector Resources'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
